- petto-api/src/main/java/com/example/petto_api/security/JwtAuthenticationTokenFilter.java
- petto-api/src/main/java/com/example/petto_api/security/JwtTokenService.java
- petto-api/src/main/java/com/example/petto_api/security/JwtUserDetails.java
- petto-api/src/main/java/com/example/petto_api/security/JwtUserDetailsService.java
- petto-api/src/main/java/com/example/petto_api/security/JwtUserFactory.java
- petto-api/src/main/java/com/example/petto_api/security/WebSecurityConfig.java
- petto-api/src/main/java/com/example/petto_api/user/UniqueEmail.java
- petto-api/src/main/java/com/example/petto_api/user/UniqueEmailValidator.java
- petto-api/src/main/java/com/example/petto_api/user/UniqueUsername.java
- petto-api/src/main/java/com/example/petto_api/user/UniqueUsernameValidator.java
- petto-api/src/main/java/com/example/petto_api/user/UserController.java
- petto-api/src/main/java/com/example/petto_api/user/UserLoginRequest.java
- petto-api/src/main/java/com/example/petto_api/user/UserModel.java
- petto-api/src/main/java/com/example/petto_api/user/UserRepository.java
- petto-api/src/main/java/com/example/petto_api/user/UserService.java
- petto-api/src/test/java/com/example/petto_api/user/UserServiceTest.java
完成功能: 
1. 註冊、登入的API
2. JWT 的操作，產生 token、檢驗 token
3. 配置 Web Security，並使其透過 JWT 驗證而非 Session 驗證
> feat: user register and login api, jwt service, web security config with jwt

- petto-api/pom.xml
- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostModel.java
- petto-api/src/main/java/com/example/petto_api/post/PostRequest.java
- petto-api/src/main/java/com/example/petto_api/post/PostService.java
- petto-api/src/main/java/com/example/petto_api/security/JwtTokenService.java
- petto-api/src/main/java/com/example/petto_api/user/UserRepository.java
- petto-api/src/main/java/com/example/petto_api/user/UserService.java
- petto-api/src/test/java/com/example/petto_api/post/PostServiceTest.java
修改原先的 controller: 透過自定義 request 格式，並檢驗是否合法，再取得 user id 並將其儲存
> feat: 建立文章

- petto-api/src/main/java/com/example/petto_api/post/PostModel.java
- petto-api/src/main/java/com/example/petto_api/reply/ReplyController.java
- petto-api/src/main/java/com/example/petto_api/reply/ReplyModel.java
- petto-api/src/main/java/com/example/petto_api/reply/ReplyRepository.java
- petto-api/src/main/java/com/example/petto_api/reply/ReplyRequest.java
- petto-api/src/main/java/com/example/petto_api/reply/ReplyService.java
- petto-api/src/main/java/com/example/petto_api/user/UserModel.java
新增 ReplyController, ReplyModel, ReplyRepository, ReplyRequest, ReplyService
修改 PostModel，因為REPLY.post_id與POST.id為FK
修改 UserModel，因為REPLY.owner與USER.id為FK
> feat: 給予留言

- petto-api/src/main/java/com/example/petto_api/Tag/DuplicateTagException.java
- petto-api/src/main/java/com/example/petto_api/Tag/TagController.java
- petto-api/src/main/java/com/example/petto_api/Tag/TagModel.java
- petto-api/src/main/java/com/example/petto_api/Tag/TagRepository.java
- petto-api/src/main/java/com/example/petto_api/Tag/TagService.java
- petto-api/src/main/java/com/example/petto_api/Tag/TagsAddRequest.java
- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostCreatedRequest.java
- petto-api/src/main/java/com/example/petto_api/post/PostModel.java
- petto-api/src/test/java/com/example/petto_api/Tag/TagServiceTest.java
add TagModel, addTags.
update PostModel, add relationship about many to many between Post and Tag.
update PostCreatedRequest, add a tags column when create post.
> feat: tag model, add tag, post contain tags

- petto-api/src/main/java/com/example/petto_api/Emoji/DuplicateEmojiException.java
- petto-api/src/main/java/com/example/petto_api/Emoji/EmojiAddRequest.java
- petto-api/src/main/java/com/example/petto_api/Emoji/EmojiController.java
- petto-api/src/main/java/com/example/petto_api/Emoji/EmojiModel.java
- petto-api/src/main/java/com/example/petto_api/Emoji/EmojiRepository.java
- petto-api/src/main/java/com/example/petto_api/Emoji/EmojiService.java
- petto-api/src/main/java/com/example/petto_api/post/PostModel.java
- petto-api/src/test/java/com/example/petto_api/Emoji/EmojiServiceTest.java
add EmojiModel, addEmojis.
update PoseModel, add relationship about many to many between Post and Emoji.
> feat: emoji model, add emoji

- petto-page/src/Components/NavBar/HomePageNavBarLogin.js
- petto-page/src/Components/NavBar/HomePageNavBarNoLogin.js
- petto-page/src/Views/Login/Login.js
- petto-page/src/Views/Register/Register.js
- petto-page/src/Views/Template/Template.js
新增註冊、登入、登出的功能和頁面
未完成: 登入時無法抓取使用者的名稱、排版還沒弄好
> feat:登出、登入、註冊

- petto-api/src/main/java/com/example/petto_api/Emoji/EmojiSeeder.java
- petto-api/src/main/java/com/example/petto_api/Tag/TagModel.java
- petto-api/src/main/java/com/example/petto_api/Tag/TagSeeder.java
- petto-api/src/main/java/com/example/petto_api/post/PostModel.java
- petto-api/src/main/java/com/example/petto_api/post/PostSeeder.java
- petto-api/src/main/java/com/example/petto_api/post/PostService.java
- petto-api/src/main/java/com/example/petto_api/seeder/DataSeeder.java
- petto-api/src/main/java/com/example/petto_api/seeder/Seeder.java
- petto-api/src/main/java/com/example/petto_api/user/UserModel.java
- petto-api/src/main/java/com/example/petto_api/user/UserSeeder.java
Add DataSeeder, PostSeeder, Seeder interface.
Refactor 架構，使其他 seeder(TagSeeder, EmojiSeeder, UserSeeder) 實現 Seeder interface，再由 DataSeeder 統一並依序執行。
修改部分 Model 的 CascadeType 為 MERGE。
> feat: PostSeeder

- petto-api/src/main/java/com/example/petto_api/Emoji/EmojiModel.java
- petto-api/src/main/java/com/example/petto_api/post/EmojiGivenRequest.java
- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostModel.java
- petto-api/src/main/java/com/example/petto_api/post/UserGivenEmojiModel.java
- petto-api/src/main/java/com/example/petto_api/post/UserGivenEmojiRepository.java
- petto-api/src/main/java/com/example/petto_api/post/UserGivenEmojiService.java
- petto-api/src/main/java/com/example/petto_api/user/UserModel.java
- petto-api/src/test/java/com/example/petto_api/post/UserGivenEmojiServiceTest.java
Add function: UserGiveEmojiToPost
Add: UserGivenEmojiModel 以及相關 Layers
Change: 修改 PostModel 和 EmojiModel 之間的關係，因為User, Post, Emoji 為三方關係，所以個別和 UserGivenEmoji 做一對多處理
> feat: user give emoji to post

- petto-api/src/main/java/com/example/petto_api/post/PostContainEmojis.java
- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostModel.java
- petto-api/src/main/java/com/example/petto_api/post/PostSeeder.java
- petto-api/src/main/java/com/example/petto_api/post/UserGivenEmojiRepository.java
- petto-api/src/main/java/com/example/petto_api/post/UserGivenEmojiService.java
Add: PostContainEmojis as POJO, countEmojiWithPost by query, API about giving emoji
> Dev api post contain emojis

- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostKeepRequest.java
- petto-api/src/main/java/com/example/petto_api/post/PostModel.java
- petto-api/src/main/java/com/example/petto_api/post/PostService.java
- petto-api/src/main/java/com/example/petto_api/user/UserModel.java
- petto-api/src/main/java/com/example/petto_api/user/UserService.java
- petto-api/src/test/java/com/example/petto_api/post/PostServiceTest.java
Add: keepPost, userHasKeptPost in PostService. keep post API in PostController.
Update: add many to many relation between UserModel and PostModel
> feat: keep post

- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostService.java
Add: getAllKeepingPosts.
Update: count and set post emojis when get post(s) in service layer.
> feat: get keeping posts

- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostCreatedRequest.java
- petto-api/src/main/java/com/example/petto_api/post/PostModel.java
- petto-api/src/main/java/com/example/petto_api/post/PostSeeder.java
- petto-api/src/main/java/com/example/petto_api/post/PostService.java
- petto-api/src/main/java/com/example/petto_api/user/UserModel.java
- petto-api/src/main/java/com/example/petto_api/vote/OptionNotExistException.java
- petto-api/src/main/java/com/example/petto_api/vote/UserHasVotingException.java
- petto-api/src/main/java/com/example/petto_api/vote/VoteController.java
- petto-api/src/main/java/com/example/petto_api/vote/VoteModel.java
- petto-api/src/main/java/com/example/petto_api/vote/VoteOptionStatistics.java
- petto-api/src/main/java/com/example/petto_api/vote/VoteRepository.java
- petto-api/src/main/java/com/example/petto_api/vote/VoteRequest.java
- petto-api/src/main/java/com/example/petto_api/vote/VoteService.java
- petto-api/src/test/java/com/example/petto_api/vote/VoteServiceTest.java
建立投票相關Model, Repository, Service, Controller
修改 Post、User Model 加入投票相關資訊(post擁有投票選項、user所投的票)
> feat: vote

- petto-page/src/Views/Post/PostList.js
修改的檔案: PostList.js
return那邊多傳type = "home"
> Postlist新增傳送參數

- petto-page/src/Views/Post/CommonCreatePost.js
修改檔案: CommonCreatePost.js
套上新的PageTemplate
> 更改CommonCreatePost模組

- petto-page/src/Components/NavBar/NavBar.js
- petto-page/src/Views/Login/Login.js
- petto-page/src/Views/Register/Register.js
- petto-page/src/Views/Template/Template.css
調整 login、register頁面
修改 template 的 CSS
> Dev page css

- petto-page/src/App/App.js
- petto-page/src/Views/Post/MdEditor.js
- petto-page/src/Views/Post/PostEditor.js
新增: 
1. PostEditor: 作為發文頁面的模板、處理 Form
2. MarkdownEditor: Markdown 語法的編輯器
修改:
1. App.js 的 Route path
> feat: md 發文

- petto-page/src/App/App.js
- petto-page/src/Views/Post/PostEditor.js
- petto-page/src/Views/Post/TextEditor.js
新增: 
1. TextEditor: 一般的發文編輯器
修改:
1. PostEditor: 加入type 顯示 TextEditor
2. App.js Route path
> feat: create text post

- petto-page/src/App/App.js
- petto-page/src/Views/Post/PostEditor.js
- petto-page/src/Views/Post/VoteEditor.js
新增:
1. VoteEditor: 投票文章的填寫區塊
修改:
1. PostEditor: 加入投票文章建立、取得內文和選項
2. App.js Route path
> feat: create vote post

- petto-page/package.json
- petto-page/src/App/App.js
- petto-page/src/Components/Emoji/Emoji.js
- petto-page/src/Components/Emoji/index.js
- petto-page/src/Views/Post/Post.js
- petto-page/src/Views/Post/Reply.js
- petto-page/src/Views/Post/index.js
新增:
1. Post.js: 單一文章的頁面
2. Reply.js: 留言的區塊
修改:
1. App.js Route path
> Dev page post

- petto-page/src/Views/Post/Post.js
- petto-page/src/Views/Post/Reply.js
> feat: reply 的顯示

- petto-page/src/Views/Post/Post.js
- petto-page/src/Views/Post/Reply.js
新增:
1. 留言功能
2. 留言完刷留言區
3. 留言完向上滾動
> feat: 留言功能

- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostRepository.java
- petto-api/src/main/java/com/example/petto_api/post/PostService.java
> feat: get user posts

- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostRepository.java
- petto-api/src/main/java/com/example/petto_api/post/PostService.java
新增:
1. PostRepository: 新增"包含"的查詢方法
2. PostService: 新增"關鍵字"查詢文章的方法
修改
1. PostController: 讓 getPosts 根據參數決定是全部還是關鍵字查詢
> feat: get post by keyword

- petto-api/src/main/java/com/example/petto_api/post/PostController.java
- petto-api/src/main/java/com/example/petto_api/post/PostService.java
- petto-api/src/main/java/com/example/petto_api/post/TagSearchRequest.java
新增:
1. PostService: 用 Set<TagModel> 搜尋文章
2. PostController: 接收 tags 來搜尋文章的 API
3. TagSearchRequest: 用於請求用 tags (id) 搜尋，接受一個 Set<Integer>
> feat: search posts by tags

- petto-page/src/Views/Post/Post.js
- petto-page/src/Views/Post/Vote.css
- petto-page/src/Views/Post/Vote.js
> feat: 投票功能和頁面
